server:
  port: 8080
---

spring:
  profiles: default
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://petfriends.cyb2gh84g1ic.us-west-2.rds.amazonaws.com:3306/petfriends?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 12341234
    
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: Payment
          destination: petfriends
          contentType: application/json
        event-out:
          destination: petfriends
          contentType: application/json

logging:
  level:
    org.hibernate.type: trace
    org.hibernate:
      type.descriptor.sql: trace #show parameter binding
      SQL: DEBUG
    org.springframework.cloud: debug
server:
  port: 8080
---

spring:
  profiles: docker
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka.kafka.svc.cluster.local:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: Payment
          destination: petfriends
          contentType: application/json
        event-out:
          destination: petfriends
          contentType: application/json
